app/main/Layout.py, app/main/events.py, app/static/plugins/mouse-tracking.js
- events.py : One mouse_position event instead of two separate events for mouse clicks and movement
- Layout.py : <audio> tag can now be used for layout injection; 'document-ready' was added as some kind of default trigger
- mouse-tracking.js : basic script for tracking mouse movement in specific html elements (such as the image area). Can be injected using the trigger 'document-ready'
=> Support for <audio> tag; new trigger; merged events mouse_move / mouse_click; basic script for tracking mouse movement

app/static/layouts/meetup-task.json, app/static/plugins/ask-reload.js, app/templates/chat.html
The prompt is annoying when rapidly reloading the page for testing.
I removed `window.unbeforeunload` from `chat.html` and moved it to a new plugin.
The default meetup task uses this plugin.
=> Make `unbeforeunload` a plugin

app/main/Layout.py, app/static/layouts/test_room.json, app/static/plugins/do-my-stuff.js
The _plain_ plugin simply copies everything from the plugin file into the _chat.html_ `<script>` section.
Please see the changed files for an example.
=> Add `plain` plugin

app/static/plugins/bounding-boxes.js
This adds a plugin for creating bounding boxes with Slurk. It can be embedded using the trigger "document-ready". 
If there's no HTML canvas element specified in the layout the plugin is used with, it picks out the image with the id "#current-image" and covers it with a canvas.
Rectangles can be drawn via mouse drag. If a user clicks on a rectangle and confirms the following dialog box, the coordinates of the rectangle are emitted as a mouse_position event. In the event data the rectangle is specified with the coordinates of its upper-left corner and its height and width. If a user clicks on the empty space around a drawn rectangle, the rectangle is deleted.
=> new plugin: bounding-boxes.js

app/main/events.py, app/static/css/chat.css, app/static/layouts/waiting_room.json, app/templates/chat.html, docs/slurk_bots.rst, sample_bots/pairup_bot.py
- ``id``: The id of the element, which is going to be updated
- ``text``: The class to be added
- ``receiver_id`` (Optional): Adds the class for this receiver only
- ``room`` (Optional): Adds the class for all receivers in this room. Either ``receiver_id`` or ``room`` is required
- ``sender_id`` (Optional): The sender of the message. Defaults to the current user
- ``id``: The id of the element, which is going to be updated
- ``text``: The class to be removed
- ``receiver_id`` (Optional): Removes the class for this receiver only
- ``room`` (Optional): Removes the class for all receivers in this room. Either ``receiver_id`` or ``room`` is required
- ``sender_id`` (Optional): The sender of the message. Defaults to the current user
=> [WIP] Add the ability to add or remove classes from html via bot commands

app/main/events.py, app/templates/chat.html, docs/slurk_bots.rst
=> [WIP] Allow `element` and `class` instead of `id` in `set_attribute`

requirements.txt, tools/start_clients.py, tools/start_server_and_bot.py
Added some features to the startup scripts: 
- the Pairup Bot is now connected by default if `start_server_and_bot.py` is run (can be prevented using the argument `--nopairup`)
- `start_server_and_bot.py` and `start_clients.py` can optionally be run with the argument `--testroom` in order to connect bots/clients to the test room
- the config file is checked for completeness in both scripts - if none exists, a new config file is created; missing entries are filled in (in most cases, exception: if no web browser is specified, the default browser is used)
- host and port are retrieved from the config file in both scripts
- exception messages for common sources of error (e.g. if the browser specified in the config file can't be found)
Two issues for Mac couldn't be solved yet:
- Opera …
=> Startupscripts update

docs/slurk_tools.rst
Added the following line to the 'tools' section:
> Please note: Both startup scripts are designed to be used for testing purposes. For actual deployment it is recommended to manually set up Slurk.
=> Added piece of advice concerning the usage of startup scripts

app/static/js/connection.js
Currently, whenever a user reloads the page, every other user in the same chat room loses their chat history and messages.
This pull request fixes this bug by clearing the chat-area only when the current user joins a new room, instead of whenever any user joins the chat room.
=> Fix chat history dissapearing on reload

app/chat/message.py
The idea is that the server reacts on `typed_message` event and emit `user_message` event to the designated room and user to show what the other user is typing. For the front end part, I think this can be managed by creating logic in `app/static/js/text.js` to handle `user_message` event. To get the current text that the user is typing, a keyup event listener can be added, which is executed when the user is typing in the chat box, where the element can be retrieved from `app/templates/chat.html` via its ID and emit `typed_message` event to the server.
=> Event for live typing mode

docker/slurk/Dockerfile, requirements.txt
SQLAlchemy changed a lot of its interfaces in 1.4 so it has to be pinned to 1.3. Also, GUnicorn required an update as it spawned infinite workers with the current version.
=> Upgrade Docker to Python 3.9 and fix dependencies

app/views/api/__init__.py, app/views/api/rooms.py, app/views/api/tasks.py, app/views/api/tokens.py, app/views/api/users.py
`dump_only` fields couldn't be set before.
The name alludes that one actually shouldn't be able to set them.
But we have this one place where `html_obj` as loadable field is saved to the
`html` dump only field. And this `html` field one should then actually be able to modify.
As there exists one field (User.token_id) that is `load_only` but
one might wish to modify, iterating over `dump_fields` is not a valid option.
=> Modify common patch method

app/models/layout.py, app/models/token.py, app/models/user.py, app/views/api/layouts.py, app/views/api/tokens.py, app/views/static/css/chat.css, app/views/static/js/connection.js, app/views/templates/chat.html, scripts/create_video_test_setup.sh
Plan: Add `video_publisher_location` and `video_subscriber_location` where an HTML Id is passed. This defaults to the Id in the header and the sidebar, but can be set to arbitrary values or even to `null` to hide the video.
=> Make video location configurable

slurk/views/login/__init__.py
The import statement `from .events import *` is necessary. If removed the `connect` event
is not caught by the appropriate socketio handler. Stripping BEARER from a token can cause
problems if the token starts with one of the letters in BEARER and it is passed alone. Additionally
the database seems to be case-sensitive so capitalizing the token_id did also cause problems.
=> Reintroduce import statement and improve request_loader

slurk/views/chat/__init__.py
Same as #168: Events are not loaded for chat namespace.
=> Import chat events again

slurk/views/api/users.py, tests/api/test_users.py
Do we need this method? Something similar existed in v2 and I couldn't find another way with the existing methods to access the user task. Something that is necessary for the concierge bot.
=> Add view to access task of user

slurk/views/api/layouts.py
Passing an invalid object as CSS for creating/altering a layout, results in an internal server error. This adds a value type to catch this error.
=> Add a value type for `"css"` field for the layout schema

scripts/start_server.sh, slurk/config.py
When setting `SLURK_DISABLE_ETAG`, it's not required anymore to pass an ETag when altering or deleting an entry.
r? @wencke-lm
=> Add option to disable ETag

slurk/views/chat/events.py
Reintroduces Event `room_created` that can be sent from a bot to slurk.
As a payload one *has* to pass the identifier of the room that was created (room.id).
One may additionally pass the identifier of a task this room was created for.
The event handler may emit up to two events.
new_room: {"room": <room_id>"} sent to all rooms and connected users
new_task_room: {"room": <room_id>, "task": <task_id>, "users": <list_of_dict {"id": <user_id>, "name": <user_name>}>} sent to all rooms and connected users
=> Add event handler for `room_created`

slurk/extensions/api.py, slurk/views/api/auth.py, slurk/views/api/rooms.py, tests/api/test_rooms.py
This adds a new decorator: `login_possible`, which adds the parameter `authorized` to the decorated function. This is a boolean value indicating if the request was made with a valid API token.
r? @wencke-lm
=> Make room logs only accessible by users logged in

slurk/models/user.py, slurk/views/static/js/connection.js
This adds a callback to the `joined_room` event. For the diff view, [whitespace changes should be hidden](https://github.com/clp-research/slurk/pull/207/files?diff=split&w=1).
r? @wencke-lm
=> Wait for status event until join has finished

docs/slurk_bots_events.rst, docs/slurk_layouts.rst, examples/enforce-fullscreen_layout.json, slurk/views/static/css/chat.css, slurk/views/static/plugins/enforce-fullscreen.js
First part of the adapted scripts from the click-bot. Might be nice to try it out on Mac, in my understanding fullscreen there is a little special. I have added an example layout to the appropriate folder.
r? @janagoetze
=> Add adapted plugin to enforce fullscreen

slurk/views/chat/events.py, slurk/views/static/plugins/mouse-tracking.js
As one may notice, so far no mouse events are logged.
Things to consider if we log mouse events on the server side as we normally do for other events:
- mouse movement on the designated html element causes an event to be triggered every 100ms, that would create hundreds of log entries
- those events are only triggered and therefore logged if the user specifies the mouse-tracking script, so the user is probably interested in logging these events
- all relevant information for each mouse event is emitted, a bot could catch that and manually save mouse events somewhere separately 
I think the slurk running on the university server has over a thousand logs by now... What is your experience working with those in terms of GETing them from the server and filtering them? Does it matter whether …
=> Add mouse-tracking plugin

docs/slurk_deployment.rst, docs/slurk_prerequisites.rst
r? @janagoetze Let's not pretend that we are the only ones who would have to ask how to do that.
Also some addition in docs/slurk_prerequisites.rst, to manually build the slurk image. For people who do not yet have a slurk image the result would be the same, no matter whether the image is pulled from GitHub or they built it themselves from the newly cloned slurk repo. But for people that already had a slurk image like Saskia, this may avoid confusion.
=> Elaborate on deployment

slurk/models/token.py, slurk/views/api/users.py, slurk/views/chat/__init__.py, tests/api/test_users.py
Partially revert https://github.com/clp-research/slurk/pull/151/commits/fcf01535bd7dc979041605801350170e119338ed
Tokens without a room still can't be used to login via the login interface (and create a user in this way), but a request can now be used to create a user from a token without a room. The advantage is, that bots waiting to join any newly created task rooms, can remain without room until they are needed. It is no longer necessary for a bot to handle events received from a room that is no task room.
=> Make room for bot tokens optional

slurk/views/static/css/chat.css, slurk/views/static/css/loadingdots.css, slurk/views/static/js/text.js, slurk/views/static/plugins/typing-users.js, slurk/views/templates/chat.html
Move the placeholder for typing-users from the display area to the chat area. It should now be more visibile to the participant. Additionally, researchers are no longer required (nor allowed) to insert a designated element into the custom display area. Passing the typing-users plugin suffices.
=> Integrate placeholder for typing-users plugin into chat layout

slurk/views/static/js/plugins.js
Timestamps are now modified so that safari will parse them correctly fixing the NaN problem in the chat.
This solution still works with firefox and chromium
=> safari-friendly date format

docs/slurk_layouts.rst, examples/collapsible-instructions_layout.json, slurk/views/static/plugins/collapsible-task-instructions.js
- add a JavaScript plugin that allows to create boxes of text (or other content) that can be shown and hidden by clicking on them
- the current use case for this is task instructions that may take up a lot of space in the main display/game area of the browser -> the user can just hide them away and show them when needed
=> Collapsible instructions

requirements.txt, slurk/views/chat/events.py, slurk/views/static/plugins/collapsible-task-instructions.js
this pull requests updates the socket-io events to reflect changes made in python-socketio => 5.8 - broadcasting events is achieved by removing the `to` or `room` parameter from the keyword arguments of the `socketio.emit()` method.
This fixes [this issue](https://github.com/clp-research/slurk/issues/255)
additional changes: minor fix to the `collapsible.js` plugin (use scope defined variables instead of defining global ones)
=> Update socketio events to new version (=> 5.8 of python socketio package)

slurk/views/chat/events.py
include the room_id in the data being sent by the start and stop typing events so that bots can also receive these events and assign them to the respective room. This information can be logged to calculate writing and idling time of a user
=> include room id to the data being transmitted by start and stop typing events

docs/slurk_deployment.rst
this pull requests provides a minimal working example of a docker-compose.yml where the data folder of the database is actually linked to the `postgres-data` directory
=> update example docker compose in documentation
