clp-research/slurk

app/main/Layout.py
app/main/Room.py
app/main/User.py
app/main/database.py
app/main/events.py
app/main/routes.py
app/static/css/chat.css
app/static/layouts/Meetup.json
app/static/layouts/single_image.json
app/static/layouts/table_layout.json
app/static/layouts/waiting_room.json
app/templates/chat.html
app/templates/layout.html
sample_bots/pairup_bot.py

This Pull Requests introduces Layouts. It also acts as example how Pull Requests are used in this repository.

Basic layouts

---

app/templates/chat.html

Fix security hole and do some formatting

---

app/main/Layout.py
app/main/Room.py
app/main/User.py
app/main/database.py
app/main/events.py
app/static/css/chat.css
app/static/layouts/default.json
app/static/layouts/meetup_task.json
app/static/layouts/waiting_room.json
app/static/plugins/plain-history.js
app/templates/chat.html
docs/index.rst
docs/slurk_bots.rst
docs/slurk_layouts.rst
sample_bots/minimal.py
sample_bots/multi_bot.py
sample_bots/pairup_bot.py

Major rewrite of layouts and plugin system. Currently work in progress.
- `set_attribute(data)`:
Sets a javascript attribute by id to a new value.
- `data`: A dictionary with the following fields:
- `id`: The id to be updated
- `attribute`: The attribute to be updated
- `value`: The value for the attribute
- `receiver_id` (Optional): Sends the attribute to this receiver only
- `room` (Optional): Sends the attribute to this room. Either `receiver_id` or `room` is required.
- `sender_id` (Optional): The sender of the message. Defaults to the current user
- `set_text(data)`:
Sets a html text element  by id to a new value.
- `data`: A dictionary with the following fields:
- `text`: The value for the attribute
- `receiver_id` (Optional): Sends the text to this receiver only
- `room` …

Some major layout adjustments and documentation

---

app/main/database.py
config.template.ini

Defaults to `botsi.db`.
Closes #12

 Make database file name configurable 

---

docs/slurk_layouts.rst

Added instructions on how to implement layouts and plugins in practice

Documentation: Layouts + Plugins

---

sample_bots/minimal.py

- replaced deprecated new_image command with set_attribute
- shifted some function definitions for a more intuitive structure of the file (registration of slash commands on top, on_print_permissions next to on_permissions)

update for minimal bot

---

.travis.yml
docs/conf.py

feat(docs): Open external links in new tab

---

app/main/Layout.py
app/templates/chat.html

Refactor loading plugins

---

CHANGELOG.md

Version 1.1: Layout and Plugins

---

sample_bots/pairup_bot.py

Changed the way the PairupBot connects to the server - it now corresponds to the login routine of the other bots. This solves issue #50 for me.

changed login routine for pairupbot

---

docs/conf.py

How the copyright notice should look like? Do we want "DSG Bielefeld" to appear somehow?

Update copyright notice in docs

---

app/static/js/plugins.js

Two different commits that fix small issues with chat messages that contain images.

Fix image chat messages

---

docs/slurk_about.rst
docs/slurk_bots.rst
docs/slurk_gettingstarted.rst
docs/slurk_layouts.rst
docs/slurk_multibots.rst

- minor text changes, mainly typos
- no changes to the content

fix some text issues

---

docs/slurk_gettingstarted.rst
docs/slurk_multibots.rst
scripts/create_room_with_layout.sh
scripts/create_task.sh
scripts/create_token.sh
scripts/create_token_for_task.sh
scripts/push_room_layout.sh

- replace server calls etc. with scripts for the multibot tutorial (creating a waiting room and task plus echo bot)
- some minor corrections in the getting started tutorial
NB: except for the waiting room layout, references are still to the sample_bots rather than the slurk-bots repository

Continue installation simplification

---

docs/index.rst
docs/slurk_prerequisites.rst

Reproduced running slurk on a Windows 10 machine using WSL2 and added documentation for this. Other users should be able to follow this guide.

Add doc to run slurk in wsl which resolves #99

---

docs/index.rst
docs/slurk_prerequisites.rst

* Add doc to run slurk in wsl which resolves #99
* Fix typos

Add doc to run slurk in wsl which resolves #99 (#100)

---

app/api/__init__.py
app/api/log.py
app/api/room.py
app/api/user.py
app/chat/message.py
app/login/__init__.py
app/login/events.py
app/models/__init__.py
app/models/user.py
app/static/js/connection.js
docker/slurk/Dockerfile
run.py

Please see the commits for each change, every commit only makes a minimal change.

Fix some bugs and make some improvements for logging in

---

app/views/api/__init__.py

Forbid passing `None` in `PATCH` method for non-null fields

---

app/extensions/api.py

Raise an error if content type does not match

---

app/views/api/layouts.py
app/views/static/layouts/default.json

Modify type of standard scripts to string

---

app/extensions/api.py

Allow content type to be empty when no content is provided

---

app/views/api/__init__.py
app/views/api/layouts.py
app/views/api/permissions.py
app/views/api/rooms.py
app/views/api/tasks.py
app/views/api/tokens.py
app/views/api/users.py

Raise 422 when foreign-key is deleted

---

app/extensions/database.py

Fix invalid access to `current_app` when running outside of app

---

app/extensions/api.py
app/views/api/__init__.py
app/views/api/rooms.py

Fix call to `extensions.api.abort`

---

app/models/layout.py
app/models/token.py
app/models/user.py
app/views/api/layouts.py
app/views/api/tokens.py
app/views/static/js/connection.js
scripts/create_video_test_setup.sh

Add paramteres to `Layout` to pass settings when connecting to OpenVidu

---

app/models/token.py
app/views/api/tokens.py
app/views/api/users.py
app/views/chat/__init__.py
app/views/login/__init__.py

Change request login to use user id

---

app/views/api/logs.py

Fix internal error when passing receiver to log

---

slurk/models/token.py
slurk/views/api/users.py
tests/api/__init__.py
tests/api/test_logs.py
tests/api/test_rooms.py
tests/api/test_users.py

Adapt user view to reduce registrations_left also
for patch and put.

Add test for `user` and `logs` table

---

slurk/models/permissions.py
slurk/models/token.py
slurk/views/api/permissions.py
slurk/views/static/js/connection.js

Add private_message attribute

---

slurk/models/log.py
slurk/views/chat/events.py

The receiver passed to the add function is an integer not a user object.

Fix parameter type mismatch

---

slurk/views/static/css/chat.css
slurk/views/static/css/login.css
slurk/views/static/css/task.css
slurk/views/static/css/token.css

r? @TimDiekmann
I didn't really find a lot of obsolete css code...
But while I was looking through the css I decided, I might as well replace the Bielefeld green 😅

css cleanup and new color scheme

---

slurk/views/__init__.py

This will be tested as PR, where auto-fix now should be disabled and after merging it should get fixed.

Test auto-fix

---

slurk/views/login/__init__.py

I received an error of this kind several times, while trying to start two bots under the same token.

Add filtering by user_id to login as request

---

slurk/extensions/openvidu.py
slurk/views/api/openvidu/__init__.py

Load openvidu config lazily

---

scripts/create_api_token.sh
scripts/create_layout.sh
scripts/create_openvidu_session.sh
scripts/create_room.sh
scripts/create_room_token.sh
scripts/create_task.sh
scripts/create_user.sh
scripts/get_logs.sh

I would suggest reading the permissions from a file, like we do with layouts.
I also adapted some of the comments that weren't correct any longer due to an earlier pull request.
r? @TimDiekmann

Read permissions for token from json file

---

scripts/start_server.sh
slurk/extensions/database.py
tests/conftest.py

Fix memory databases for sqlite

---

slurk/models/room.py
slurk/views/api/rooms.py
slurk/views/chat/events.py
slurk/views/static/js/connection.js
tests/api/test_rooms.py

Add `read_only` attribute to rooms

---

slurk/views/api/layouts.py

Cherry-pick from #213  to avoid failing CI
r? @wencke-lm

Fix OpenAPI for union types in specs

---

.github/workflows/docs.yml
docs/conf.py
docs/slurk_api.rst

Remove OpenAPI generation from sphinx

---

slurk/views/api/openvidu/__init__.py

Return 501 when OpenVidu is not enabled but requested

---

slurk/views/static/plugins/bounding-boxes.js
slurk/views/static/plugins/mouse-tracking.js

Add prefix to script variable names

---

docs/conf.py

- update copyright notice with date
@davidschlangen  fyi

update copyright notice

---

docs/conf.py
docs/slurk_permissions.rst

Correct docs

---

docs/conf.py
slurk/models/log.py
slurk/views/api/tasks.py
slurk/views/api/tokens.py
tests/api/test_tasks.py
tests/api/test_tokens.py

it doesn't log the room id but a query, so it doesn't belong here.

do not log db queries

---

docs/slurk_layouts.rst
slurk/views/chat/events.py
slurk/views/static/plugins/live-typing.js

@janagoetze r?
I am not sure about the latency problem that was mentioned here https://github.com/clp-research/slurk/pull/103 as I am only testing on localhost.

Preliminary live-typing mode

---

slurk/views/chat/events.py

fixes https://github.com/clp-research/slurk/issues/232

correct entity name

---

docs/slurk_layouts.rst
slurk/views/chat/events.py
slurk/views/static/js/text.js
slurk/views/static/plugins/keylogger.js

keylogging plugin to log every keystroke of the users in slurk logs

Keylogging

---

slurk/views/chat/events.py
slurk/views/static/plugins/keylogger.js

this commit fixes a problem which prevents slurk from creating a log entry for the keystroke event.
the keylogger plugin works correctly and keystrokes are saved in the logs

fixed keylogger bug during log creation

---

slurk/views/api/users.py

add new API call to get permission based on user_id. This call will only return the permissions of a user if the token can no longer be used to log into slurk. This way we prevent rendering the token useless for future logins

add new API call to get permission based on user_id

---

docs/slurk_api.rst

add info about internal/external database behaviour with example

add info about internal/external database behaviour
